name: Ruby Gem Publish

on:
  push:
    tags: 
      - '*'
jobs:
  publish:
    runs-on: ubuntu-latest
    env:
      GEM_HOST_API_KEY: ${{ secrets.GEM_HOST_API_KEY }}
    
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: '2.6'
          bundler-cache: false

      # Comment this out and test it
      #- uses: actions/setup-node@v2

      - name: Publish
        run: |
          mkdir -p $HOME/.gem
          printf -- "---\n:rubygems_api_key: ${API_KEY}\n" > $HOME/.gem/credentials
          VERSION=${GITHUB_REF#refs/*/} make publish
        env:
          API_KEY: "${{secrets.GEM_HOST_API_KEY}}"